In [ ]:
import glob, os, csv, json, orjson
from tqdm import tqdm
import pandas as pd
from tableone import TableOne

In [10]:
snowmed_map = pd.read_csv("snowmed_map.csv")
# Convert the SNOWMED CT Code to string
snowmed_map["SNOMED CT Code"] = snowmed_map["SNOMED CT Code"].astype(str)
snowmed_map = snowmed_map.set_index("SNOMED CT Code").to_dict(orient="index")
snowmed_map

{'270492004': {'Dx': '1st degree av block', 'Abbreviation': 'IAVB'},
 '195042002': {'Dx': '2nd degree av block', 'Abbreviation': 'IIAVB'},
 '164951009': {'Dx': 'abnormal QRS', 'Abbreviation': 'abQRS'},
 '426664006': {'Dx': 'accelerated junctional rhythm', 'Abbreviation': 'AJR'},
 '57054005': {'Dx': 'acute myocardial infarction', 'Abbreviation': 'AMI'},
 '413444003': {'Dx': 'acute myocardial ischemia', 'Abbreviation': 'AMIs'},
 '426434006': {'Dx': 'anterior ischemia', 'Abbreviation': 'AnMIs'},
 '54329005': {'Dx': 'anterior myocardial infarction', 'Abbreviation': 'AnMI'},
 '251173003': {'Dx': 'atrial bigeminy', 'Abbreviation': 'AB'},
 '164889003': {'Dx': 'atrial fibrillation', 'Abbreviation': 'AF'},
 '195080001': {'Dx': 'atrial fibrillation and flutter',
  'Abbreviation': 'AFAFL'},
 '164890007': {'Dx': 'atrial flutter', 'Abbreviation': 'AFL'},
 '195126007': {'Dx': 'atrial hypertrophy', 'Abbreviation': 'AH'},
 '251268003': {'Dx': 'atrial pacing pattern', 'Abbreviation': 'AP'},
 '713422000': {'Dx': 'atrial tachycardia', 'Abbreviation': 'ATach'},
 '29320008': {'Dx': 'atrioventricular junctional rhythm',
  'Abbreviation': 'AVJR'},
 '233917008': {'Dx': 'av block', 'Abbreviation': 'AVB'},
 '251170000': {'Dx': 'blocked premature atrial contraction',
  'Abbreviation': 'BPAC'},
 '74615001': {'Dx': 'brady tachy syndrome', 'Abbreviation': 'BTS'},
 '426627000': {'Dx': 'bradycardia', 'Abbreviation': 'Brady'},
 '6374002': {'Dx': 'bundle branch block', 'Abbreviation': 'BBB'},
 '698247007': {'Dx': 'cardiac dysrhythmia', 'Abbreviation': 'CD'},
 '426749004': {'Dx': 'chronic atrial fibrillation', 'Abbreviation': 'CAF'},
 '413844008': {'Dx': 'chronic myocardial ischemia', 'Abbreviation': 'CMI'},
 '27885002': {'Dx': 'complete heart block', 'Abbreviation': 'CHB'},
 '713427006': {'Dx': 'complete right bundle branch block',
  'Abbreviation': 'CRBBB'},
 '204384007': {'Dx': 'congenital incomplete atrioventricular heart block',
  'Abbreviation': 'CIAHB'},
 '53741008': {'Dx': 'coronary heart disease', 'Abbreviation': 'CHD'},
 '77867006': {'Dx': 'decreased qt interval', 'Abbreviation': 'SQT'},
 '82226007': {'Dx': 'diffuse intraventricular block', 'Abbreviation': 'DIB'},
 '428417006': {'Dx': 'early repolarization', 'Abbreviation': 'ERe'},
 '13640000': {'Dx': 'fusion beats', 'Abbreviation': 'FB'},
 '84114007': {'Dx': 'heart failure', 'Abbreviation': 'HF'},
 '368009': {'Dx': 'heart valve disorder', 'Abbreviation': 'HVD'},
 '251259000': {'Dx': 'high t-voltage', 'Abbreviation': 'HTV'},
 '49260003': {'Dx': 'idioventricular rhythm', 'Abbreviation': 'IR'},
 '251120003': {'Dx': 'incomplete left bundle branch block',
  'Abbreviation': 'ILBBB'},
 '713426002': {'Dx': 'incomplete right bundle branch block',
  'Abbreviation': 'IRBBB'},
 '251200008': {'Dx': 'indeterminate cardiac axis', 'Abbreviation': 'ICA'},
 '425419005': {'Dx': 'inferior ischaemia', 'Abbreviation': 'IIs'},
 '704997005': {'Dx': 'inferior ST segment depression', 'Abbreviation': 'ISTD'},
 '426995002': {'Dx': 'junctional escape', 'Abbreviation': 'JE'},
 '251164006': {'Dx': 'junctional premature complex', 'Abbreviation': 'JPC'},
 '426648003': {'Dx': 'junctional tachycardia', 'Abbreviation': 'JTach'},
 '425623009': {'Dx': 'lateral ischaemia', 'Abbreviation': 'LIs'},
 '445118002': {'Dx': 'left anterior fascicular block',
  'Abbreviation': 'LAnFB'},
 '253352002': {'Dx': 'left atrial abnormality', 'Abbreviation': 'LAA'},
 '67741000119109': {'Dx': 'left atrial enlargement', 'Abbreviation': 'LAE'},
 '446813000': {'Dx': 'left atrial hypertrophy', 'Abbreviation': 'LAH'},
 '39732003': {'Dx': 'left axis deviation', 'Abbreviation': 'LAD'},
 '164909002': {'Dx': 'left bundle branch block', 'Abbreviation': 'LBBB'},
 '445211001': {'Dx': 'left posterior fascicular block',
  'Abbreviation': 'LPFB'},
 '164873001': {'Dx': 'left ventricular hypertrophy', 'Abbreviation': 'LVH'},
 '370365005': {'Dx': 'left ventricular strain', 'Abbreviation': 'LVS'},
 '251146004': {'Dx': 'low qrs voltages', 'Abbreviation': 'LQRSV'},
 '54016002': {'Dx': 'mobitz type i wenckebach atrioventricular block',
  'Abbreviation': 'MoI'},
 '164865005': {'Dx': 'myocardial infarction', 'Abbreviation': 'MI'},
 '164861001': {'Dx': 'myocardial ischemia', 'Abbreviation': 'MIs'},
 '698252002': {'Dx': 'nonspecific intraventricular conduction disorder',
  'Abbreviation': 'NSIVCB'},
 '428750005': {'Dx': 'nonspecific st t abnormality', 'Abbreviation': 'NSSTTA'},
 '164867002': {'Dx': 'old myocardial infarction', 'Abbreviation': 'OldMI'},
 '10370003': {'Dx': 'pacing rhythm', 'Abbreviation': 'PR'},
 '251182009': {'Dx': 'paired ventricular premature complexes',
  'Abbreviation': 'VPVC'},
 '282825002': {'Dx': 'paroxysmal atrial fibrillation', 'Abbreviation': 'PAF'},
 '67198005': {'Dx': 'paroxysmal supraventricular tachycardia',
  'Abbreviation': 'PSVT'},
 '425856008': {'Dx': 'paroxysmal ventricular tachycardia',
  'Abbreviation': 'PVT'},
 '284470004': {'Dx': 'premature atrial contraction', 'Abbreviation': 'PAC'},
 '427172004': {'Dx': 'premature ventricular contractions',
  'Abbreviation': 'PVC'},
 '17338001': {'Dx': 'ventricular premature beats', 'Abbreviation': 'VPB'},
 '164947007': {'Dx': 'prolonged pr interval', 'Abbreviation': 'LPR'},
 '111975006': {'Dx': 'prolonged qt interval', 'Abbreviation': 'LQT'},
 '164917005': {'Dx': 'qwave abnormal', 'Abbreviation': 'QAb'},
 '164921003': {'Dx': 'r wave abnormal', 'Abbreviation': 'RAb'},
 '314208002': {'Dx': 'rapid atrial fibrillation', 'Abbreviation': 'RAF'},
 '253339007': {'Dx': 'right atrial abnormality', 'Abbreviation': 'RAAb'},
 '446358003': {'Dx': 'right atrial hypertrophy', 'Abbreviation': 'RAH'},
 '47665007': {'Dx': 'right axis deviation', 'Abbreviation': 'RAD'},
 '59118001': {'Dx': 'right bundle branch block', 'Abbreviation': 'RBBB'},
 '89792004': {'Dx': 'right ventricular hypertrophy', 'Abbreviation': 'RVH'},
 '55930002': {'Dx': 's t changes', 'Abbreviation': 'STC'},
 '49578007': {'Dx': 'shortened pr interval', 'Abbreviation': 'SPRI'},
 '65778007': {'Dx': 'sinoatrial block', 'Abbreviation': 'SAB'},
 '427393009': {'Dx': 'sinus arrhythmia', 'Abbreviation': 'SA'},
 '426177001': {'Dx': 'sinus bradycardia', 'Abbreviation': 'SB'},
 '60423000': {'Dx': 'sinus node dysfunction', 'Abbreviation': 'SND'},
 '426783006': {'Dx': 'sinus rhythm', 'Abbreviation': 'NSR'},
 '427084000': {'Dx': 'sinus tachycardia', 'Abbreviation': 'STach'},
 '429622005': {'Dx': 'st depression', 'Abbreviation': 'STD'},
 '164931005': {'Dx': 'st elevation', 'Abbreviation': 'STE'},
 '164930006': {'Dx': 'st interval abnormal', 'Abbreviation': 'STIAb'},
 '251168009': {'Dx': 'supraventricular bigeminy', 'Abbreviation': 'SVB'},
 '63593006': {'Dx': 'supraventricular premature beats',
  'Abbreviation': 'SVPB'},
 '426761007': {'Dx': 'supraventricular tachycardia', 'Abbreviation': 'SVT'},
 '251139008': {'Dx': 'suspect arm ecg leads reversed', 'Abbreviation': 'ALR'},
 '164934002': {'Dx': 't wave abnormal', 'Abbreviation': 'TAb'},
 '59931005': {'Dx': 't wave inversion', 'Abbreviation': 'TInv'},
 '266257000': {'Dx': 'transient ischemic attack', 'Abbreviation': 'TIA'},
 '164937009': {'Dx': 'u wave abnormal', 'Abbreviation': 'UAb'},
 '11157007': {'Dx': 'ventricular bigeminy', 'Abbreviation': 'VBig'},
 '164884008': {'Dx': 'ventricular ectopics', 'Abbreviation': 'VEB'},
 '75532003': {'Dx': 'ventricular escape beat', 'Abbreviation': 'VEsB'},
 '81898007': {'Dx': 'ventricular escape rhythm', 'Abbreviation': 'VEsR'},
 '164896001': {'Dx': 'ventricular fibrillation', 'Abbreviation': 'VF'},
 '111288001': {'Dx': 'ventricular flutter', 'Abbreviation': 'VFL'},
 '266249003': {'Dx': 'ventricular hypertrophy', 'Abbreviation': 'VH'},
 '251266004': {'Dx': 'ventricular pacing pattern', 'Abbreviation': 'VPP'},
 '195060002': {'Dx': 'ventricular pre excitation', 'Abbreviation': 'VPEx'},
 '164895002': {'Dx': 'ventricular tachycardia', 'Abbreviation': 'VTach'},
 '251180001': {'Dx': 'ventricular trigeminy', 'Abbreviation': 'VTrig'},
 '195101003': {'Dx': 'wandering atrial pacemaker', 'Abbreviation': 'WAP'},
 '74390002': {'Dx': 'wolff parkinson white pattern', 'Abbreviation': 'WPW'}}

In [ ]:
with open("/sailhome/kelvinkn/scr2_juice/code15_final_results.json", "r") as f:
    data = orjson.loads(f.read())

# with open("code15_test.json", "w", encoding="utf-8") as f:
#     f.write(orjson.dumps(data, option=orjson.OPT_INDENT_2).decode("utf-8"))

In [3]:
classes_map = {
    "RBBB":   "59118001",
    "LBBB":   "164909002",
    "SB":     "426177001",
    "ST":     "427084000",
    "AF":     "164889003",
    "1dAVb":  "270492004"
}

# Computing Accuracy of Prna

In [4]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

def extract_label_pairs(records, classes_map):
    y_true = []
    y_pred = []

    for rec in records:
        snowmed = rec.get("snowmed_vals", {})
        for label, code in classes_map.items():
            if code in snowmed:
                entry = snowmed[code]
                if "present" in entry and "actual_present" in entry:
                    y_true.append(entry["actual_present"])
                    y_pred.append(entry["present"])
    return y_true, y_pred

# Assume records is already loaded (e.g. from previous step)
# And classes_map is defined
y_true, y_pred = extract_label_pairs(data, classes_map)

# Overall metrics
acc = accuracy_score(y_true, y_pred)
prec, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary")

print("=== Classification Metrics ===")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

=== Classification Metrics ===
Accuracy:  0.9449
Precision: 0.2272
Recall:    0.9111
F1 Score:  0.3637

In [16]:
report = classification_report(y_true, y_pred, target_names=["Negative", "Positive"])
print(report)

              precision    recall  f1-score   support

    Negative       1.00      0.95      0.97   2019643
    Positive       0.23      0.91      0.36     35537

    accuracy                           0.94   2055180
   macro avg       0.61      0.93      0.67   2055180
weighted avg       0.99      0.94      0.96   2055180

In [17]:
with open("table1/classification_metrics.txt", "w") as f:
    f.write("=== Classification Metrics (Binary) ===\n")
    f.write(f"Accuracy:  {acc:.4f}\n")
    f.write(f"Precision: {prec:.4f}\n")
    f.write(f"Recall:    {recall:.4f}\n")
    f.write(f"F1 Score:  {f1:.4f}\n\n")
    f.write("=== Classification Report ===\n")
    f.write(report)

print(f"✅ Saved classification metrics to table1/classification_metrics.txt")

✅ Saved classification metrics to table1/classification_metrics.txt

In [6]:
import pandas as pd

def compute_per_label_metrics(records, classes_map):
    results = []

    for label, code in classes_map.items():
        y_true = []
        y_pred = []

        for rec in records:
            snowmed = rec.get("snowmed_vals", {})
            if code in snowmed:
                entry = snowmed[code]
                if "present" in entry and "actual_present" in entry:
                    y_true.append(entry["actual_present"])
                    y_pred.append(entry["present"])

        if y_true:  # Only compute if there are valid entries
            acc = accuracy_score(y_true, y_pred)
            prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary", zero_division=0)
            results.append({
                "label": label,
                "snomed_code": code,
                "n_samples": len(y_true),
                "accuracy": acc,
                "precision": prec,
                "recall": rec,
                "f1": f1
            })

    return pd.DataFrame(results)
label_metrics_df = compute_per_label_metrics(data, classes_map)
label_metrics_df

   label snomed_code  n_samples  accuracy  precision    recall        f1
0   RBBB    59118001     342530  0.927703   0.265491  0.909972  0.411054
1   LBBB   164909002     342530  0.986804   0.581973  0.869362  0.697213
2     SB   426177001     342530  0.853587   0.096874  0.964016  0.176056
3     ST   427084000     342530  0.979564   0.521207  0.917779  0.664847
4     AF   164889003     342530  0.981356   0.522866  0.899004  0.661184
5  1dAVb   270492004     342530  0.940201   0.000000  0.000000  0.000000

In [14]:
label_metrics_df.to_csv("table1/code15_label_metrics.csv", index=False)

# Chagas Analysis

## Prna's predicted snowmed codes

In [8]:
from tableone import TableOne

def records_to_tableone_df(records, classes_map):
    rows = []

    for rec in records:
        row = {"chagas": rec.get("chagas", False)}
        for label, code in classes_map.items():
            val = rec.get("snowmed_vals", {}).get(code)
            if val:
                row[label] = val.get("actual_present", False)
            else:
                row[label] = None  # missing condition
        rows.append(row)

    return pd.DataFrame(rows)

table1_full_snowmed_df = records_to_tableone_df(data, classes_map)

# Define categorical variables
categorical = list(classes_map.keys())

# Create the table
table1 = TableOne(data=table1_full_snowmed_df, columns=categorical, categorical=categorical, groupby="chagas", pval=True)

# Display or export
print(table1)

                   Grouped by chagas
                             Missing         Overall           False          True P-Value
n                                             342530          335978          6552
RBBB, n (%)  False                     333033 (97.2)   327791 (97.6)   5242 (80.0)  <0.001
             True                         9497 (2.8)      8187 (2.4)   1310 (20.0)
LBBB, n (%)  False                     336544 (98.3)   330215 (98.3)   6329 (96.6)  <0.001
             True                         5986 (1.7)      5763 (1.7)     223 (3.4)
SB, n (%)    False                     336972 (98.4)   330628 (98.4)   6344 (96.8)  <0.001
             True                         5558 (1.6)      5350 (1.6)     208 (3.2)
ST, n (%)    False                     334965 (97.8)   328516 (97.8)   6449 (98.4)  <0.001
             True                         7565 (2.2)      7462 (2.2)     103 (1.6)
AF, n (%)    False                     335599 (98.0)   329450 (98.1)   6149 (93.8)  <0.001
             True                         6931 (2.0)      6528 (1.9)     403 (6.2)
1dAVb, n (%) False                    342530 (100.0)  335978 (100.0)  6552 (100.0)   1.000

In [13]:
table1.to_csv("table1/table1_prna_snowmed.csv", index=False)

## All Snowmed's codes

In [18]:
def flatten_records_for_tableone(records):
    data = []

    for rec in records:
        row = {"chagas": rec.get("chagas", False)}
        for code, val in rec.get("snowmed_vals", {}).items():
            abbrev = snowmed_map[code]['Abbreviation']
            if "actual_present" in val:
                present = val["actual_present"]
                row[f"{abbrev}_ACTUAL"] = present
            present = val.get("present")
            row[f"{abbrev}_PRED"] = present
        data.append(row)

    return pd.DataFrame(data)

table1_flattened_df = flatten_records_for_tableone(data)

# All SNOMED columns (those starting with 'SNOMED_') are categorical
snomed_cols = [col for col in table1_flattened_df.columns if col.endswith("ACTUAL") or col.endswith("PRED")]

# Generate the table
table1_all_snowmed = TableOne(data=table1_flattened_df, columns=snomed_cols, categorical=snomed_cols, groupby="chagas", pval=True)


# table1_all_snowmed.to_csv("table1_chagas_vs_all_snomed.csv")

In [19]:
print(table1_all_snowmed)

                          Grouped by chagas
                                    Missing         Overall           False          True P-Value
n                                                    342530          335978          6552
PR_PRED, n (%)      False                     342055 (99.9)   335593 (99.9)   6462 (98.6)  <0.001
                    True                          475 (0.1)       385 (0.1)      90 (1.4)
LQT_PRED, n (%)     False                     328728 (96.0)   322463 (96.0)   6265 (95.6)   0.154
                    True                        13802 (4.0)     13515 (4.0)     287 (4.4)
AF_ACTUAL, n (%)    False                     335599 (98.0)   329450 (98.1)   6149 (93.8)  <0.001
                    True                         6931 (2.0)      6528 (1.9)     403 (6.2)
AF_PRED, n (%)      False                     330613 (96.5)   324822 (96.7)   5791 (88.4)  <0.001
                    True                        11917 (3.5)     11156 (3.3)    761 (11.6)
AFL_PRED, n (%)     False                     340688 (99.5)   334242 (99.5)   6446 (98.4)  <0.001
                    True                         1842 (0.5)      1736 (0.5)     106 (1.6)
LBBB_ACTUAL, n (%)  False                     336544 (98.3)   330215 (98.3)   6329 (96.6)  <0.001
                    True                         5986 (1.7)      5763 (1.7)     223 (3.4)
LBBB_PRED, n (%)    False                     333588 (97.4)   327403 (97.4)   6185 (94.4)  <0.001
                    True                         8942 (2.6)      8575 (2.6)     367 (5.6)
QAb_PRED, n (%)     False                     340759 (99.5)   334230 (99.5)   6529 (99.6)   0.071
                    True                         1771 (0.5)      1748 (0.5)      23 (0.4)
TAb_PRED, n (%)     False                     312751 (91.3)   306941 (91.4)   5810 (88.7)  <0.001
                    True                        29779 (8.7)     29037 (8.6)    742 (11.3)
LPR_PRED, n (%)     False                     342358 (99.9)  335814 (100.0)   6544 (99.9)   0.018
                    True                          172 (0.1)       164 (0.0)       8 (0.1)
VPB_PRED, n (%)     False                     337061 (98.4)   330755 (98.4)   6306 (96.2)  <0.001
                    True                         5469 (1.6)      5223 (1.6)     246 (3.8)
LQRSV_PRED, n (%)   False                     342247 (99.9)   335708 (99.9)   6539 (99.8)   0.002
                    True                          283 (0.1)       270 (0.1)      13 (0.2)
IAVB_ACTUAL, n (%)  False                    342530 (100.0)  335978 (100.0)  6552 (100.0)   1.000
IAVB_PRED, n (%)    False                     322047 (94.0)   316352 (94.2)   5695 (86.9)  <0.001
                    True                        20483 (6.0)     19626 (5.8)    857 (13.1)
PAC_PRED, n (%)     False                     322252 (94.1)   316176 (94.1)   6076 (92.7)  <0.001
                    True                        20278 (5.9)     19802 (5.9)     476 (7.3)
LAD_PRED, n (%)     False                     325792 (95.1)   319789 (95.2)   6003 (91.6)  <0.001
                    True                        16738 (4.9)     16189 (4.8)     549 (8.4)
SB_ACTUAL, n (%)    False                     336972 (98.4)   330628 (98.4)   6344 (96.8)  <0.001
                    True                         5558 (1.6)      5350 (1.6)     208 (3.2)
SB_PRED, n (%)      False                     287221 (83.9)   281983 (83.9)   5238 (79.9)  <0.001
                    True                       55309 (16.1)    53995 (16.1)   1314 (20.1)
Brady_PRED, n (%)   False                     339760 (99.2)   333289 (99.2)   6471 (98.8)  <0.001
                    True                         2770 (0.8)      2689 (0.8)      81 (1.2)
NSR_PRED, n (%)     False                     140562 (41.0)   135998 (40.5)   4564 (69.7)  <0.001
                    True                      201968 (59.0)   199980 (59.5)   1988 (30.3)
STach_ACTUAL, n (%) False                     334965 (97.8)   328516 (97.8)   6449 (98.4)  <0.001
                    True                         7565 (2.2)      7462 (2.2)     103 (1.6)
STach_PRED, n (%)   False                     329209 (96.1)   322870 (96.1)   6339 (96.7)   0.008
                    True                        13321 (3.9)     13108 (3.9)     213 (3.3)
PVC_PRED, n (%)     False                     339913 (99.2)   333505 (99.3)   6408 (97.8)  <0.001
                    True                         2617 (0.8)      2473 (0.7)     144 (2.2)
SA_PRED, n (%)      False                     320192 (93.5)   313811 (93.4)   6381 (97.4)  <0.001
                    True                        22338 (6.5)     22167 (6.6)     171 (2.6)
LAnFB_PRED, n (%)   False                     340868 (99.5)   334356 (99.5)   6512 (99.4)   0.166
                    True                         1662 (0.5)      1622 (0.5)      40 (0.6)
RAD_PRED, n (%)     False                     341158 (99.6)   334641 (99.6)   6517 (99.5)   0.103
                    True                         1372 (0.4)      1337 (0.4)      35 (0.5)
RBBB_ACTUAL, n (%)  False                     333033 (97.2)   327791 (97.6)   5242 (80.0)  <0.001
                    True                         9497 (2.8)      8187 (2.4)   1310 (20.0)
RBBB_PRED, n (%)    False                     309979 (90.5)   305249 (90.9)   4730 (72.2)  <0.001
                    True                        32551 (9.5)     30729 (9.1)   1822 (27.8)
TInv_PRED, n (%)    False                     338340 (98.8)   331893 (98.8)   6447 (98.4)   0.006
                    True                         4190 (1.2)      4085 (1.2)     105 (1.6)
SVPB_PRED, n (%)    False                    342495 (100.0)  335945 (100.0)  6550 (100.0)   0.144
                    True                           35 (0.0)        33 (0.0)       2 (0.0)
NSIVCB_PRED, n (%)  False                     342255 (99.9)   335723 (99.9)   6532 (99.7)  <0.001
                    True                          275 (0.1)       255 (0.1)      20 (0.3)
IRBBB_PRED, n (%)   False                     328957 (96.0)   322992 (96.1)   5965 (91.0)  <0.001
                    True                        13573 (4.0)     12986 (3.9)     587 (9.0)
CRBBB_PRED, n (%)   False                     341037 (99.6)   334653 (99.6)   6384 (97.4)  <0.001
                    True                         1493 (0.4)      1325 (0.4)     168 (2.6)

In [20]:
table1_all_snowmed.to_csv("table1_chagas_vs_all_snomed.csv")

In [10]:
print(table1_all_snowmed)

                              Grouped by chagas
                                        Missing         Overall           False          True P-Value
n                                                        342530          335978          6552
SNOMED_10370003, n (%)  False                     342055 (99.9)   335593 (99.9)   6462 (98.6)  <0.001
                        True                          475 (0.1)       385 (0.1)      90 (1.4)
SNOMED_111975006, n (%) False                     328728 (96.0)   322463 (96.0)   6265 (95.6)   0.154
                        True                        13802 (4.0)     13515 (4.0)     287 (4.4)
SNOMED_164889003, n (%) False                     335599 (98.0)   329450 (98.1)   6149 (93.8)  <0.001
                        True                         6931 (2.0)      6528 (1.9)     403 (6.2)
SNOMED_164890007, n (%) False                     340688 (99.5)   334242 (99.5)   6446 (98.4)  <0.001
                        True                         1842 (0.5)      1736 (0.5)     106 (1.6)
SNOMED_164909002, n (%) False                     336544 (98.3)   330215 (98.3)   6329 (96.6)  <0.001
                        True                         5986 (1.7)      5763 (1.7)     223 (3.4)
SNOMED_164917005, n (%) False                     340759 (99.5)   334230 (99.5)   6529 (99.6)   0.071
                        True                         1771 (0.5)      1748 (0.5)      23 (0.4)
SNOMED_164934002, n (%) False                     312751 (91.3)   306941 (91.4)   5810 (88.7)  <0.001
                        True                        29779 (8.7)     29037 (8.6)    742 (11.3)
SNOMED_164947007, n (%) False                     342358 (99.9)  335814 (100.0)   6544 (99.9)   0.018
                        True                          172 (0.1)       164 (0.0)       8 (0.1)
SNOMED_17338001, n (%)  False                     337061 (98.4)   330755 (98.4)   6306 (96.2)  <0.001
                        True                         5469 (1.6)      5223 (1.6)     246 (3.8)
SNOMED_251146004, n (%) False                     342247 (99.9)   335708 (99.9)   6539 (99.8)   0.002
                        True                          283 (0.1)       270 (0.1)      13 (0.2)
SNOMED_270492004, n (%) False                    342530 (100.0)  335978 (100.0)  6552 (100.0)   1.000
SNOMED_284470004, n (%) False                     322252 (94.1)   316176 (94.1)   6076 (92.7)  <0.001
                        True                        20278 (5.9)     19802 (5.9)     476 (7.3)
SNOMED_39732003, n (%)  False                     325792 (95.1)   319789 (95.2)   6003 (91.6)  <0.001
                        True                        16738 (4.9)     16189 (4.8)     549 (8.4)
SNOMED_426177001, n (%) False                     336972 (98.4)   330628 (98.4)   6344 (96.8)  <0.001
                        True                         5558 (1.6)      5350 (1.6)     208 (3.2)
SNOMED_426627000, n (%) False                     339760 (99.2)   333289 (99.2)   6471 (98.8)  <0.001
                        True                         2770 (0.8)      2689 (0.8)      81 (1.2)
SNOMED_426783006, n (%) False                     140562 (41.0)   135998 (40.5)   4564 (69.7)  <0.001
                        True                      201968 (59.0)   199980 (59.5)   1988 (30.3)
SNOMED_427084000, n (%) False                     334965 (97.8)   328516 (97.8)   6449 (98.4)  <0.001
                        True                         7565 (2.2)      7462 (2.2)     103 (1.6)
SNOMED_427172004, n (%) False                     339913 (99.2)   333505 (99.3)   6408 (97.8)  <0.001
                        True                         2617 (0.8)      2473 (0.7)     144 (2.2)
SNOMED_427393009, n (%) False                     320192 (93.5)   313811 (93.4)   6381 (97.4)  <0.001
                        True                        22338 (6.5)     22167 (6.6)     171 (2.6)
SNOMED_445118002, n (%) False                     340868 (99.5)   334356 (99.5)   6512 (99.4)   0.166
                        True                         1662 (0.5)      1622 (0.5)      40 (0.6)
SNOMED_47665007, n (%)  False                     341158 (99.6)   334641 (99.6)   6517 (99.5)   0.103
                        True                         1372 (0.4)      1337 (0.4)      35 (0.5)
SNOMED_59118001, n (%)  False                     333033 (97.2)   327791 (97.6)   5242 (80.0)  <0.001
                        True                         9497 (2.8)      8187 (2.4)   1310 (20.0)
SNOMED_59931005, n (%)  False                     338340 (98.8)   331893 (98.8)   6447 (98.4)   0.006
                        True                         4190 (1.2)      4085 (1.2)     105 (1.6)
SNOMED_63593006, n (%)  False                    342495 (100.0)  335945 (100.0)  6550 (100.0)   0.144
                        True                           35 (0.0)        33 (0.0)       2 (0.0)
SNOMED_698252002, n (%) False                     342255 (99.9)   335723 (99.9)   6532 (99.7)  <0.001
                        True                          275 (0.1)       255 (0.1)      20 (0.3)
SNOMED_713426002, n (%) False                     328957 (96.0)   322992 (96.1)   5965 (91.0)  <0.001
                        True                        13573 (4.0)     12986 (3.9)     587 (9.0)
SNOMED_713427006, n (%) False                     341037 (99.6)   334653 (99.6)   6384 (97.4)  <0.001
                        True                         1493 (0.4)      1325 (0.4)     168 (2.6)

,Unnamed: 0,Unnamed: 1,Grouped by chagas,Grouped by chagas.1,Grouped by chagas.2,Grouped by chagas.3,Grouped by chagas.4
0,NaN,NaN,Missing,Overall,False,True,P-Value
1,n,NaN,NaN,342530,335978,6552,NaN
2,"SNOMED_10370003, n (%)",False,NaN,342055 (99.9),335593 (99.9),6462 (98.6),<0.001
3,"SNOMED_10370003, n (%)",True,NaN,475 (0.1),385 (0.1),90 (1.4),NaN
4,"SNOMED_111975006, n (%)",False,NaN,328728 (96.0),322463 (96.0),6265 (95.6),0.154
5,"SNOMED_111975006, n (%)",True,NaN,13802 (4.0),13515 (4.0),287 (4.4),NaN
6,"SNOMED_164889003, n (%)",False,NaN,330613 (96.5),324822 (96.7),5791 (88.4),<0.001
7,"SNOMED_164889003, n (%)",True,NaN,11917 (3.5),11156 (3.3),761 (11.6),NaN
8,"SNOMED_164890007, n (%)",False,NaN,340688 (99.5),334242 (99.5),6446 (98.4),<0.001
9,"SNOMED_164890007, n (%)",True,NaN,1842 (0.5),1736 (0.5),106 (1.6),NaN
10,"SNOMED_164909002, n (%)",False,NaN,333588 (97.4),327403 (97.4),6185 (94.4),<0.001
11,"SNOMED_164909002, n (%)",True,NaN,8942 (2.6),8575 (2.6),367 (5.6),NaN
12,"SNOMED_164917005, n (%)",False,NaN,340759 (99.5),334230 (99.5),6529 (99.6),0.071
13,"SNOMED_164917005, n (%)",True,NaN,1771 (0.5),1748 (0.5),23 (0.4),NaN
14,"SNOMED_164934002, n (%)",False,NaN,312751 (91.3),306941 (91.4),5810 (88.7),<0.001
15,"SNOMED_164934002, n (%)",True,NaN,29779 (8.7),29037 (8.6),742 (11.3),NaN
16,"SNOMED_164947007, n (%)",False,NaN,342358 (99.9),335814 (100.0),6544 (99.9),0.018
17,"SNOMED_164947007, n (%)",True,NaN,172 (0.1),164 (0.0),8 (0.1),NaN
18,"SNOMED_17338001, n (%)",False,NaN,337061 (98.4),330755 (98.4),6306 (96.2),<0.001
19,"SNOMED_17338001, n (%)",True,NaN,5469 (1.6),5223 (1.6),246 (3.8),NaN
20,"SNOMED_251146004, n (%)",False,NaN,342247 (99.9),335708 (99.9),6539 (99.8),0.002
21,"SNOMED_251146004, n (%)",True,NaN,283 (0.1),270 (0.1),13 (0.2),NaN
22,"SNOMED_270492004, n (%)",False,NaN,322047 (94.0),316352 (94.2),5695 (86.9),<0.001
23,"SNOMED_270492004, n (%)",True,NaN,20483 (6.0),19626 (5.8),857 (13.1),NaN
24,"SNOMED_284470004, n (%)",False,NaN,322252 (94.1),316176 (94.1),6076 (92.7),<0.001
25,"SNOMED_284470004, n (%)",True,NaN,20278 (5.9),19802 (5.9),476 (7.3),NaN
26,"SNOMED_39732003, n (%)",False,NaN,325792 (95.1),319789 (95.2),6003 (91.6),<0.001
27,"SNOMED_39732003, n (%)",True,NaN,16738 (4.9),16189 (4.8),549 (8.4),NaN
28,"SNOMED_426177001, n (%)",False,NaN,287221 (83.9),281983 (83.9),5238 (79.9),<0.001
29,"SNOMED_426177001, n (%)",True,NaN,55309 (16.1),53995 (16.1),1314 (20.1),NaN
30,"SNOMED_426627000, n (%)",False,NaN,339760 (99.2),333289 (99.2),6471 (98.8),<0.001
31,"SNOMED_426627000, n (%)",True,NaN,2770 (0.8),2689 (0.8),81 (1.2),NaN
32,"SNOMED_426783006, n (%)",False,NaN,140562 (41.0),135998 (40.5),4564 (69.7),<0.001
33,"SNOMED_426783006, n (%)",True,NaN,201968 (59.0),199980 (59.5),1988 (30.3),NaN
34,"SNOMED_427084000, n (%)",False,NaN,329209 (96.1),322870 (96.1),6339 (96.7),0.008
35,"SNOMED_427084000, n (%)",True,NaN,13321 (3.9),13108 (3.9),213 (3.3),NaN
36,"SNOMED_427172004, n (%)",False,NaN,339913 (99.2),333505 (99.3),6408 (97.8),<0.001
37,"SNOMED_427172004, n (%)",True,NaN,2617 (0.8),2473 (0.7),144 (2.2),NaN
38,"SNOMED_427393009, n (%)",False,NaN,320192 (93.5),313811 (93.4),6381 (97.4),<0.001
39,"SNOMED_427393009, n (%)",True,NaN,22338 (6.5),22167 (6.6),171 (2.6),NaN
40,"SNOMED_445118002, n (%)",False,NaN,340868 (99.5),334356 (99.5),6512 (99.4),0.166
41,"SNOMED_445118002, n (%)",True,NaN,1662 (0.5),1622 (0.5),40 (0.6),NaN
42,"SNOMED_47665007, n (%)",False,NaN,341158 (99.6),334641 (99.6),6517 (99.5),0.103
43,"SNOMED_47665007, n (%)",True,NaN,1372 (0.4),1337 (0.4),35 (0.5),NaN
44,"SNOMED_59118001, n (%)",False,NaN,309979 (90.5),305249 (90.9),4730 (72.2),<0.001
45,"SNOMED_59118001, n (%)",True,NaN,32551 (9.5),30729 (9.1),1822 (27.8),NaN
46,"SNOMED_59931005, n (%)",False,NaN,338340 (98.8),331893 (98.8),6447 (98.4),0.006
47,"SNOMED_59931005, n (%)",True,NaN,4190 (1.2),4085 (1.2),105 (1.6),NaN
48,"SNOMED_63593006, n (%)",False,NaN,342495 (100.0),335945 (100.0),6550 (100.0),0.144
49,"SNOMED_63593006, n (%)",True,NaN,35 (0.0),33 (0.0),2 (0.0),NaN
50,"SNOMED_698252002, n (%)",False,NaN,342255 (99.9),335723 (99.9),6532 (99.7),<0.001
51,"SNOMED_698252002, n (%)",True,NaN,275 (0.1),255 (0.1),20 (0.3),NaN
52,"SNOMED_713426002, n (%)",False,NaN,328957 (96.0),322992 (96.1),5965 (91.0),<0.001
53,"SNOMED_713426002, n (%)",True,NaN,13573 (4.0),12986 (3.9),587 (9.0),NaN
54,"SNOMED_713427006, n (%)",False,NaN,341037 (99.6),334653 (99.6),6384 (97.4),<0.001
55,"SNOMED_713427006, n (%)",True,NaN,1493 (0.4),1325 (0.4),168 (2.6),NaN

In [5]:
table1_all_snowmed.to_csv("/sailhome/kelvinkn/scr2_juice/other_work/edwards/table1/table1_chagas_all_snowmed_no_ground_truth.csv")

In [12]:
import os
os.getcwd()

'/juice2/scr2/kelvinkn'